from object import Object
from message import Message
from animation import Animation
from audio import Audio
from callback_query import CallbackQuery
from chat import Chat
from chat_photo import ChatPhoto
from chat_member import ChatMember
from contect import Contact
from date import Date
